source "https://rubygems.org"

gem "jekyll", "~> 4.0"
gem "kramdown-parser-gfm"
gem "webrick"

group :jekyll_plugins do
  gem "just-the-docs"
  #gem "jekyll-theme-minima"
  #gem "jekyll-theme-hacker"

  gem "jekyll-default-layout"
  # This one spams the GitHub API to hell and back for no good reason:
  # https://github.com/jekyll/github-metadata/issues/266
  # gem "jekyll-github-metadata"
  gem "jekyll-optional-front-matter"
  gem "jekyll-readme-index"
  gem "jekyll-relative-links"
  gem "jekyll-titles-from-headings"

  # This doesn't support Jekyll 4, and Jekyll 3 is ancient.
  # https://github.com/TWiStErRob/twisterrob.github.io/issues/23
  # https://github.com/github/pages-gem/issues/651#issuecomment-1197448026
  # gem "github-pages"
end
